### ISSUE TITLE
Can't resolve './bootstrap-styles' and Can't resolve './bootstrap-scripts'

### ISSUE THREAD

**Issue by Redigast13** [shakacode/bootstrap-loader#199] opened 2016-11-05 12:12 UTC
I'm trying to use bootstrap-loader in [this angular 2 project](https://github.com/AngularClass/angular2-webpack-starter). webpack compilation outputs errors:

```
ERROR in ./~/bootstrap-webpack/index.js
Module not found: Error: Can't resolve './bootstrap-styles' in 'd:\web\angular2-webpack-starter\node_modules\bootstrap-webpack'
 @ ./~/bootstrap-webpack/index.js 1:0-66
 @ ./src/vendor.browser.ts
 @ multi vendor

ERROR in ./~/bootstrap-webpack/index.js
Module not found: Error: Can't resolve './bootstrap-scripts' in 'd:\web\angular2-webpack-starter\node_modules\bootstrap-webpack'
 @ ./~/bootstrap-webpack/index.js 2:0-52
 @ ./src/vendor.browser.ts
 @ multi vendor
```

Steps to reproduce:

1. clone `https://github.com/AngularClass/angular2-webpack-starter`
2. `npm install`
3. `npm install bootstrap-webpack --save`
4. `npm install less-loader less --save-dev`
5. add line: `require("bootstrap-webpack");` to `src/vendor.browser.ts`
6. add some rules to `config/webpack.common.js` from bootstrap-webpack documentation:
```
// bootstrap-webpack has access to the jQuery object
{ test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },
// Needed for the css-loader when [bootstrap-webpack](https://github.com/bline/bootstrap-webpack)
// loads bootstrap's css.
{ test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,   loader: "url?limit=10000&mimetype=application/font-woff" },
{ test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,    loader: "url?limit=10000&mimetype=application/octet-stream" },
{ test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,    loader: "file" },
{ test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,    loader: "url?limit=10000&mimetype=image/svg+xml" }
```
7. `npm start`

**Comment by justin808** [comment] 2016-11-15 04:50
You might be having issues with windows paths. If you can submit a PR demonstrating the issue and a fix, I'll merge it. I bet there's some mistake in some config, however.

**Comment by noonie2k** [comment] 2017-02-14 19:07
I have the exact same issue on Linux

```
ERROR in ./~/bootstrap-webpack/index.js
Module not found: Error: Can't resolve './bootstrap-styles' in '/home/adam/development/personal/my-app/node_modules/bootstrap-webpack'
 @ ./~/bootstrap-webpack/index.js 3:0-66
 @ multi bootstrap-webpack ./app

ERROR in ./~/bootstrap-webpack/index.js
Module not found: Error: Can't resolve './bootstrap-scripts' in '/home/adam/development/personal/my-app/node_modules/bootstrap-webpack'
 @ ./~/bootstrap-webpack/index.js 4:0-52
 @ multi bootstrap-webpack ./app
```

This occurs when I use `require('bootstrap-webpack');` in my `index.js` OR include `entry: ['bootstrap-webpack', './app']` in my `webpack.config.js` file.

This is a new app I'm working on and have only followed the instructions in the README

**Comment by justin808** [comment] 2017-02-14 22:17
@noonie2k Take a look at the other open issues. There's a bunch of churn going on right now with the Webpack v2 updates (including the extract-text-plugin). If you discover something needing a PR, please let me know.

**Comment by leefsmp** [comment] 2017-02-25 19:47
I have the same issue, did you find out how to fix this? Thanks

**Comment by aarkerio** [comment] 2017-02-26 18:42
Same here on Debian with Node 6.10 and webpack 2.2.1

**Comment by justin808** [comment] 2017-02-26 19:27
@Judahmeek and I will try to get an update out in the next couple of days.

**Comment by pawanpoudel** [comment] 2017-03-03 22:24
This issue seems to be caused by the [bootstrap-webpack](https://github.com/gowravshekar/bootstrap-webpack) package not [bootstrap-loader](https://github.com/shakacode/bootstrap-loader). I just verified that [this pull request](https://github.com/gowravshekar/bootstrap-webpack/pull/35) already fixes the issue and it has been merged into `master`. 

However, the [NPM package registry](https://www.npmjs.com/package/bootstrap-webpack) shows that `0.0.5` is the latest version which was published about a year ago. Hopefully, the maintainers of that package will publish a new version soon and this issue will go away. In the mean time, if you go to the `node_modules/bootstrap-webpack` in your project root directory and replace the contents of `index.js` file with the following code, the error should go away.

```javascript
require("style-loader!css-loader!less-loader!./bootstrap-styles.loader!./bootstrap.config.js");
require("./bootstrap-scripts.loader!./bootstrap.config.js");
```

The root cause of the issue is that Webpack 2.x no longer allows us to omit the `-loader` suffix when using loaders. The current version (`0.0.5`) of the [bootstrap-webpack](https://github.com/gowravshekar/bootstrap-webpack) package uses `bootstrap-scripts` and `bootstrap-styles` instead of the full name of the loader files: `bootstrap-scripts.loader` and `bootstrap-styles.loader` in the `index.js` file. That's why Webpack says it can't find those modules.

**Comment by justin808** [comment] 2017-04-06 08:44
@pawanpoudel what does the bootstrap-webpack package have to do with this repo?

**Comment by justin808** [comment] 2017-04-06 08:44
I'll reopen if you feel we should.

**Closed by justin808** 2017-04-06 08:44 UTC
Labels: question
