### ISSUE TITLE
 Cannot find module './lib/bootstrap.loader!./no-op.js' when using on server

### ISSUE THREAD

**Issue by okendoken** [shakacode/bootstrap-loader#41] opened 2016-02-11 09:53 UTC
When using bootstrap loader on a server getting the following error:

```
Error: Cannot find module './lib/bootstrap.loader!./no-op.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (d:\projects\react-dashboard\node_modules\bootstrap-loader\loader.js:1:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

Adding bootstrap-loader to an entry point does not work:

```
entry: ['bootstrap-loader', './src/client.js'],
```

Refs: https://github.com/kriasoft/react-starter-kit/issues/179

**Comment by alexfedoseev** [comment] 2016-02-11 11:13
@okendoken Please create a repo thus I can reproduce it. Thanks!

**Comment by jenyckee** [comment] 2016-02-16 15:37
same error https://github.com/jenyckee/webpack-webapp

**Comment by alexfedoseev** [comment] 2016-02-16 15:48
@jenyckee Can you load `bootstrap-loader` from entry point of webpack config (instead of requiring it from app file) and post here how it works?

**Comment by nelseric** [comment] 2016-02-16 21:57
I get this error when using bootstrap loader in my CI ( using poltergeist (phantomjs 2.0.1) ), both with using the entrypoint and requiring it. I don't get the error when running locally

**Comment by jenyckee** [comment] 2016-02-17 08:03
@alexfedoseev I tried that. Gives me the same error.

**Comment by nelseric** [comment] 2016-02-17 18:15
I seem to have solved this by upgrading my nodejs version ( to 5.1 ) even though it is a runtime error

**Comment by alexfedoseev** [comment] 2016-02-18 10:21
@nelseric @jenyckee Can you uncomment `loglevel: debug` in config and post here the output from console.

**Comment by jenyckee** [comment] 2016-02-19 13:16
I didn't used to but now I get an error about the babel polyfill missing too. However, this is the full output

```

> webpack@0.0.1 start /Users/jenyckee/Appstrakt/frontend-standard-webpack
> node .

[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
 --------------------------------------
          UI: http://localhost:3001
 --------------------------------------
[BS] Serving files from: app
[BS] Watching files...
webpack: wait until bundle finished: /
webpack built ad3dff1f409531bb2031 in 1357ms
Hash: ad3dff1f409531bb2031
Version: webpack 1.12.13
Time: 1357ms
     Asset       Size  Chunks             Chunk Names
   main.js    12.2 kB       0  [emitted]  main
index.html  331 bytes          [emitted]  
chunk    {0} main.js (main) 10 kB [rendered]
    [0] multi main 52 bytes {0} [built] [1 error]
    [1] ./~/bootstrap-loader/loader.js 46 bytes {0} [built] [1 error]
    [2] ./~/css-loader!./~/sass-loader!./app/css/main.scss 185 bytes {0} [built]
    [3] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [4] ./~/style-loader/addStyles.js 7.21 kB {0} [built]
    [5] ./app/css/main.scss 1.04 kB {0} [built]

ERROR in multi main
Module not found: Error: Cannot resolve module 'babel' in /Users/jenyckee/Appstrakt/frontend-standard-webpack
 @ multi main

ERROR in 
      For Node <= v0.12.x Babel polyfill is required.
      Make sure it's installed in your 'node_modules/' directory.
    
 @ ./~/bootstrap-loader/loader.js 1:0-44
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  426 kB       0       
    chunk    {0} index.html 412 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./app/index.ejs 546 bytes {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/index.js 411 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.

```

**Comment by AllenFang** [comment] 2016-02-19 13:53
@jenyckee, for bootstrap-load, if node.js <= 0.12, you need install ```babel-polyfill``` or ```babel/polyfill```

**Comment by jenyckee** [comment] 2016-02-19 13:56
I know, still same.
```
npm install -save babel-polyfill
```
right?

**Comment by AllenFang** [comment] 2016-02-19 14:03
yes, but what's the version of babel you used? I think for the user of babel@5,  babel/polyfill is necessary instead of babel-polyfill

**Comment by jenyckee** [comment] 2016-02-19 14:25
the issue might be due to this
https://phabricator.babeljs.io/T7077

**Comment by AllenFang** [comment] 2016-02-20 08:25
@jenyckee why, I can't get this babel issue

**Comment by alexfedoseev** [comment] 2016-02-21 19:02
@jenyckee Can you post small repo to reproduce the problem?

**Comment by justin808** [comment] 2016-02-27 07:41
I'm not sure we support a version as old as nodejs v0.10.33

I'm going to close this one. Please re-open an issue and preferably submit a PR if you still have an issue. Thanks.

**Comment by chuilee** [comment] 2016-03-13 12:26
was it  resoled? I got this problem too

**Comment by AllenFang** [comment] 2016-03-13 12:47
I thinks a clear version of Node.js and babel is required for solve this issue, if a repo can reproduce this problem will be best

**Comment by chuilee** [comment] 2016-03-15 01:43
@AllenFang thanks . I use node v4.3.1. it is ok now

**Comment by jenyckee** [comment] 2016-03-15 11:29
I upgraded my node version too and it works. However at our servers we can not upgrade atm to higher node versions. For this reason I think it's recommended to get it running on lower node versions too.

**Comment by justin808** [comment] 2016-03-16 06:08
@jenyckee I'm happy to take a PR, either doc or code.

**Comment by mdgraser** [comment] 2016-03-16 22:57
@justin808 Won't [this](https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L11-L12) always throw with node < 4 because no one is using more than one version of babel?

**Comment by justin808** [comment] 2016-03-16 23:16
![2016-03-16_13-15-41](https://cloud.githubusercontent.com/assets/1118459/13831620/38406b52-eb79-11e5-9b5b-9c53909bf277.png)

That's an @AllenFang question.

**Comment by AllenFang** [comment] 2016-03-17 01:40
#29 that's my problems

**Comment by Vishwaas** [comment] 2016-04-25 20:17
It seem to happen in node v4.2.6 too but for file-loader

**Comment by Vishwaas** [comment] 2016-04-25 20:20
It happens to me too, I have node V.4.2.6 but for file-loader

**Comment by justin808** [comment] 2016-04-26 00:58
Fixed by https://github.com/shakacode/bootstrap-loader/pull/29

**Comment by justin808** [comment] 2016-04-26 00:58
Actually, I'm not sure now. @Vishwaas, @mdgraser Anything we need to change? Or all good?

**Comment by cdax** [comment] 2016-07-28 10:36
Still seeing this with node v4.4.7

**Comment by cvle** [comment] 2016-07-30 08:58
confirm

**Comment by peterjp80** [comment] 2016-08-05 03:23
I was seeing this too with node v5.4.1 when using require('bootstrap-loader'), but when I put as an entry instead it worked.

**Comment by justin808** [comment] 2016-08-05 03:38
Does anybody have any preference to what we do? Should we just change the documentation to only use the webpack entry point?

**Comment by mxmtsk** [comment] 2016-09-13 19:41
I just wanted to follow up if anyone has made some progress? I'm using the latest node (but tried v5.12.0 too) and I'm getting 

```
Error: Cannot find module './lib/bootstrap.loader!./no-op.js'
```

I'm using react-starter-kit and I can't get my head around how to solve the error on server side.

**Comment by michaeljota** [comment] 2016-09-16 18:14
Hello. I'm having this issue with `Node 6.5.0`, `boostrap 4.0.0-alpha.4` and `bootstrap-loader 2.0.0-beta.11`. 
I'm requiring it in vendor.js. What's the appropiate usage of this? I mean, if I should not require it, and have to use it in webpack.config.js, how to do it?

**Comment by justin808** [comment] 2016-09-16 23:06
@mxmtsk @michaeljota Maybe you can take a look at: https://forum.shakacode.com/t/debugging-nodejs-and-webpack-loaders/142

I'm happy to accept a PR that's reviewed and confirmed by at least one other community member.

**Comment by Judahmeek** [comment] 2016-09-17 07:55
@mxmtsk @michaeljota Do you have public repositories? Any issues running bootstrap-loaders' examples? @cdax @cvle @peterjp80 Have any of you resolved your issue?

**Comment by mxmtsk** [comment] 2016-09-17 10:28
@Judahmeek No, it's not public but I'm using the popular https://github.com/kriasoft/react-starter-kit and did not change anything in the webpack config except adding bootstrap-loader.

My bootstraprc looks like this, just in case:
https://gist.github.com/mxmtsk/3676c9440abbe319e3ae17bd3c59190e

**Comment by michaeljota** [comment] 2016-09-17 10:44
I'm using the [n2-admin](https://github.com/akveo/ng2-admin) seed. And I'm trying to update Angular to 2.0 and Bootstrap to Alpha.4, but when I do this gets throwed. 

I have a fork of the n2-admin, [here](https://github.com/michaeljota/ng2-admin). I will sync those updates to a feature branch and let you know.

**Comment by crebuh** [comment] 2016-09-29 11:30
I've got the same issue with Node v4.4.4, Angular-Universal 2.0.11 and webpack 2.1.0-beta.22

**Comment by Judahmeek** [comment] 2016-09-30 02:22
@crebuh Can you reproduce your issue in a public repository?

@mxmtsk Have you compared your attempt to https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/tree/add-bootstrap-loader-1.2?

@michaeljota There are branches of that fork that use bootstrap-loader. If investigating those doesn't solve your problem, then I look forward to your feature branch.

@everyone There's nothing in our code or file structure that directly leads to this error. This error is caused by bad combinations of Node version, Babel version, Webpack configuration, etc and is a unique issue every time. None of you actually have the same issue and the only way I'm going to help solve these is if you provide me with public repositories that replicate the issue so I know that I have all the information I need.

**Comment by mxmtsk** [comment] 2016-09-30 08:46
@Judahmeek He integrated it the same way as I did, but he also didn't add the bootstrap-loader in the webpacks server entry part of the configuration. So he has the exact same issue as me

**Comment by crebuh** [comment] 2016-09-30 10:49
@Judahmeek 

here is a gist of my webpack.config file. I'm working on a project based on the Angular-Universal-Starter repo (https://github.com/angular/universal)

you mentioned babel I'm not using it at all. I guess the problem is the webpack config.

https://gist.github.com/crebuh/25878e08e712a56fdc1a701130103be1

**Comment by Judahmeek** [comment] 2016-09-30 22:33
@mxmtsk Not sure which branch you are referring to, but https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/tree/add-bootstrap-loader-1.2 does not reproduce this issue (granted you have to install style-loader & bootstrap-sass in addition to the listed dependencies, but once that's done, Webpack runs without errors). Feel free to clone and run my implementation: https://ide.c9.io/judahmeek/rsbl

**Comment by mxmtsk** [comment] 2016-09-30 22:46
@Judahmeek Have a look at tools/webpack.config.js line 261, there is the entry point for the server config which is missing bootstrap-loader. if you add bootstrap-loader there (to solve the flash of unstyled content) it's throwing the error!

**Comment by Judahmeek** [comment] 2016-09-30 22:58
@mxmtsk So it does. I'll let you know once I have an answer for this.

**Comment by Judahmeek** [comment] 2016-10-01 02:53
@mxmtsk I think I've identified the cause: kriasoft/react-starter-kit#892

**Comment by Judahmeek** [comment] 2016-10-01 03:00
@crebuh Your externals function looks like it's probably also the issue. Throw a `console.log` in there to see what it catches.

**Comment by FakhruddinAbdi** [comment] 2016-10-01 06:21
@Judahmeek and @mxmtsk, both the error and the flash  of unstyled content has been solved in this PR already : https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/pull/3

But it's not a permanent solution because it use isomorphic style loader to take the bootstrap-loader output and put it into the DOM directly.

I'm following your solution @Judahmeek .

**Comment by crebuh** [comment] 2016-10-11 09:37
@Judahmeek 

yes I need this function to import modules on the server-side. I'm using the angular-universal-starter project. I've tried to debug the function. When I include the bootstrap-loader like: 

      entry: ['bootstrap-loader', './src/client']

I got 'bootstrap-loader' as request param within checkNodeImport. I can check for this and do some different like for other modules? Any advice on that? e.g. return a file-path, basically to achieve the same loading-procedure like for the client.

**Comment by Judahmeek** [comment] 2016-10-13 05:57
@crebuh Assuming I'm interpreting it correctly, your checkNodeImport function externalizes every request that is not an absolute or relative path (so all module requests). Your options are to either request bootstrap-loader with an absolute or relative path, narrow your range of valid externalizable requests through regex, etc, or add the `bootstrap-loader` to some sort of exclusion list within the checkNodeImport function.

**Comment by lironess** [comment] 2016-10-22 23:26
I'm also getting that message, node v6.7.0
is there any other version that can work for now (until it will be fixed) ?

**Comment by Judahmeek** [comment] 2016-10-23 00:22
@lironess If you are getting this error, it means that node is trying to require the webpack query in https://github.com/shakacode/bootstrap-loader/blob/master/loader.js

The cause of this is usually an overly broad externals definition in your webpack.config.

**Comment by mxmtsk** [comment] 2016-10-23 12:03
It's no working for me by following this PR (thanks @FakhruddinAbdi) https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/pull/3

It doesn't work with the original bootstrap-loader sadly but maybe we're getting closer with a solution that may fit everybody

**Comment by Judahmeek** [comment] 2016-10-24 03:43
@mxmtsk I'm not sure why it wouldn't work for you. I just cloned the the repository here: https://ide.c9.io/judahmeek/rsbl, ran `git checkout add-bootstrap-loader-1.2`, ran `npm install`, ran `npm install react@^15.3.2`, ran `npm run start` and webpack worked without error.

**Comment by crebuh** [comment] 2016-10-24 08:20
@Judahmeek 

thx for the advise. Instead of loading bootstrap via the webpack config, I'm just requiring it in my app.node.module, which should included BS already on the server side. I'm doing the following:

     require('../node_modules/bootstrap-loader/lib/bootstrap.loader');

Now I'm getting the following message in the console, and it seems that the styles are also not inserted correctly. It's quite weird.

    WARNING in ./~/bootstrap-loader/lib/bootstrap.loader.js
    184:105 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/bootstrap-loader/lib/bootstrap.loader.js
    192:106 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/bootstrap-loader/lib/utils/checkBootstrapVersion.js
    9:19 Critical dependency: the request of a dependency is an expression

I also tried require('../node_modules/bootstrap-loader/loader'), which doesnt wortk

**Comment by davidtran** [comment] 2016-10-25 09:55
I have this issue on node v4.2.6

**Comment by Judahmeek** [comment] 2016-10-25 16:15
@crebuh That is weird, but you're not giving me enough information to debug this. According to http://stackoverflow.com/questions/37000273/critical-dependencies-the-request-of-a-dependency-is-an-expression-webpack, that error means that those require statements have variables for parameters instead of strings. You should be able to solve this with some debugging. If not, try this: https://github.com/AngularClass/angular2-webpack-starter/issues/993#issuecomment-246883410

**Comment by Judahmeek** [comment] 2016-10-25 16:17
@davidtran Show me your webpack config. This error only occurs when webpack is treating `bootstrap-loader` as an external dependency instead of as a loader. This is usually due to an overly broad exterbals definition: https://webpack.github.io/docs/configuration.html#externals

**Comment by gholol** [comment] 2016-12-30 22:09
Got this error just now when I used npm update

It was working fine until this
God this is annoying

**Comment by justin808** [comment] 2017-04-06 08:48
Closing for now since no activity since October, 2016.

**Closed by justin808** 2017-04-06 08:48 UTC
Labels: question, waiting on reporter

**Comment by hafeez1042** [comment] 2017-04-17 18:59
Same error 
Node Version: 6.10.2
Webpack Version: 2.4.1

**Comment by justin808** [comment] 2017-04-17 22:23
@hafeez1042 You'll need to provide a sample github project to demonstrate this issue.

**Comment by davidfurlong** [comment] 2017-06-08 08:18
I resolved this issue by

1) Trying to enable debug mode and figuring out that my `bootstrap.config.js` config that I was using was not working - replaced it with a `.bootstraprc` which then allowed me to enable debug and showed that my `.bootstraprc` was missing a couple of fields.

**Comment by davidfurlong** [comment] 2017-10-31 21:13
Full circle! Back with this issue 👎

**Comment by derwaldgeist** [comment] 2018-01-16 18:39
I got this error when I was running my app's main index.js file (including redux provider and router) through jest for testing purposes. Maybe it's because no real DOM is available in this case, although I've enabled jsdom? In the browser, everything works as expected.

**Comment by hafidsmail** [comment] 2018-07-18 08:04
Having the same problem and still giving me the same error `ERROR in ./node_modules/bootstrap-loader/no-op.js`

**Comment by BeOleg** [comment] 2019-08-27 21:44
same here +1

**Comment by skinderis** [comment] 2020-03-11 14:05
Does someone have a solution?

**Comment by Judahmeek** [comment] 2020-04-28 16:07
@skinderis There are multiple reasons that users encounter this error so each user's solution is likely to be unique. Creating a small repo (or linking to it if it's public) that reproduces your configuration & error is the simplest way to enable someone to determine the cause of your error.

We welcome PRs from anyone who thinks they can improve the user-friendliness of this package.
