### ISSUE TITLE
Error: Final loader didn't return a Buffer or String

### ISSUE THREAD

**Issue by nfort** [shakacode/bootstrap-loader#77] opened 2016-04-07 20:17 UTC
i get this error, when try compile

```
ERROR in ./~/style/style.js!./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (/Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
    at nextLoader (/Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
    at nextLoader (/Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/noxfort/PhpstormProjects/oktell-calls/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/Users/noxfort/PhpstormProjects/oktell-calls/node_modules/css-loader/lib/loader.js:116:3)
    at /Users/noxfort/PhpstormProjects/oktell-calls/node_modules/css-loader/lib/processCss.js:199:3
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:0-92
```

How it fix?

```
var webpack = require('webpack');

module.exports = {
    entry: ['bootstrap-loader', './resources/assets/app/app.js'],
    output: {
        path: __dirname,
        filename: './public/assets/bundle.js'
    },
    resolve: {
        modulesDirectories: ["web_modules", "node_modules", "resources/assets/bower_components"]
    },
    plugins: [
        new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin(".bower.json", ["main"])
        ),
        new webpack.ProvidePlugin({
            '$': 'jquery',
            'jQuery': 'jquery'
            // 'ReactDOM':   'react-dom',
            // 'cssModule':  'react-css-modules',
        })
    ],
    module: {
        loaders: [
            {
                test: /\.less$/,
                loader: "style!css!less"
            },
            {
                test: /\.css$/, loader: "style!css"
            },
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel', // 'babel-loader' is also a legal name to reference
                query: {
                    presets: ['es2015']
                }
            },
            {
                test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff'
            },
            {
                test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream'
            },
            {
                test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file'
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml'
            }
        ]
    }
};
```

**Comment by alexfedoseev** [comment] 2016-04-07 21:14
@nfort Do you have all required loaders installed?

```
css-loader node-sass resolve-url-loader sass-loader style-loader url-loader
```

If yes, then, please, post small repo to reproduce the issue.

**Comment by keithrob** [comment] 2016-04-25 03:07
@alexfedoseev,
I had the same problem and your complete list of required modules fixed it.  Thx.

```
npm install css-loader node-sass resolve-url-loader sass-loader\
 style-loader url-loader --save-dev
```

Might want to add that to the README.md's Installation section.

**Comment by alexfedoseev** [comment] 2016-04-25 06:47
@keithrob Glad it helped 👍 

> Might want to add that to the README.md's Installation section.

Actually [it's there](https://github.com/shakacode/bootstrap-loader#installation)

@nfort 
I'm closing this for now. Reopen if issue still occurs.

**Closed by alexfedoseev** 2016-04-25 06:47 UTC

**Comment by szhang6** [comment] 2017-03-15 06:27
Hit this issue when compile and seems above install command not work. Any advice?


ERROR in
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (D:\git_workspace\node_modules\webpack-core\lib\NormalModuleMixin.js:299:42)
    at nextLoader (D:\git_workspace\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at DependenciesBlock.onLoadPitchDone (D:\git_workspace\node_modules\webpack-core\lib\NormalModuleMixin.js:262:4)
    at DependenciesBlock.loadPitch (D:\git_workspace\node_modules\webpack-core\lib\NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (D:\git_workspace\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (D:\git_workspace\node_modules\webpack\lib\NormalModule.js:84:14)
    at Compilation.buildModule (D:\git_workspace\node_modules\webpack\lib\Compilation.js:126:9)
    at D:\git_workspace\node_modules\webpack\lib\Compilation.js:309:10
    at D:\git_workspace\node_modules\webpack\lib\NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\git_workspace\node_modules\tapable\lib\Tapable.js:75:69)
    at onDoneResolving (D:\git_workspace\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
    at onDoneResolving (D:\git_workspace\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
    at D:\git_workspace\node_modules\webpack\lib\NormalModuleFactory.js:116:7
    at D:\git_workspace\node_modules\async\lib\async.js:726:13
    at D:\git_workspace\node_modules\async\lib\async.js:52:16
    at async.forEachOf.async.eachOf (D:\git_workspace\node_modules\async\lib\async.js:236:30)
 @ ./src/main_zxx.js 37:8-19

**Comment by justin808** [comment] 2017-04-06 08:41
@szhang6 can you try on Mac OS or Linux?

**Comment by szhang6** [comment] 2017-04-10 06:13
This issue has been resolved which is caused by not import the right file. After correct the import statement, then the program run normally.

**Comment by szhang6** [comment] 2017-04-10 06:13
Thanks @justin808

**Comment by shivashankargalla** [comment] 2017-06-11 15:06
can you please tell which import statement was wrong and which file? @szhang6
