### ISSUE TITLE
 Bootstrap 3 use Webpack 2.1.0-beta.25 encounter the resolve-url-loader error

### ISSUE THREAD

**Issue by silveryiris** [shakacode/bootstrap-loader#185] opened 2016-09-30 08:37 UTC
This was ok on `Webpack 2.1.0-beta.22` ,
but broken on `Webpack 2.1.0-beta.25` 

```
ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: TypeError: Cannot read property 'path' of undefined
    at Object.resolveUrlLoader (PROJECT_LOCATION\node_modules\resolve-url-loader\index.js:38:55)
 @ ./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 4:14-164
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
 @ ./~/bootstrap-loader/loader.js
 @ multi home
```

My packages :
`webpack 2.1.0-beta.25`
`bootstrap-loader 2.0.0-beta.11`
`resolve-url-loader 1.6.0`

Webpack config

``` javascript
    {
        name: 'Client',
        entry: {
            home: [
                 "bootstrap-loader","./client/home.js"
            ],
            vendor: ["aos", "aos/dist/aos.css", "jquery", "picturefill"]
        },
        output: {
            path: './public/js',
            filename: "[name].chunk.js"
        },
        resolve: {
            modules: ["node_modules"],
            descriptionFiles: ["package.json"],
            alias: {},
            extensions: [".js", ".styl", ".scss"]
        },
        module: {
            noParse: [path.resolve(__dirname, "public")],
            rules: [
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: [
                        {
                            loader: 'babel'
                        }
                    ]
                }, {
                    test: /\.css$/,
                    use: [
                        {
                            loader: 'style'
                        }, {
                            loader: 'css'
                        }
                    ]
                }, {
                    test: /.styl$/,
                    use: [
                        {
                            loader: 'style'
                        }, {
                            loader: 'css'
                        }, {
                            loader: 'stylus'
                        }
                    ]
                }, {
                    test: /.scss$/,
                    use: [
                        {
                            loader: 'style'
                        }, {
                            loader: 'css'
                        }, {
                            loader: 'sass'
                        }
                    ]
                }, {
                    test: /\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/,
                    use: [
                        {
                            loader: 'url',
                            options: {
                                limit: '100000',
                                name: '[name].[ext]'
                            }
                        }
                    ]

                }
            ]
        },
        plugins: [
            new webpack.optimize.CommonsChunkPlugin({name: "vendor", filename: "vendor.js"}),
            new webpack.ProvidePlugin({"$": "jquery", "jQuery": "jquery", "window.jQuery": "jquery"}),
            new webpack.LoaderOptionsPlugin({
                options: {
                    stylus: {
                        use: [nib()],
                        import: [path.resolve(__dirname, 'node_modules/nib/lib/nib/index.styl')]
                    },
                    context: __dirname
                }
            })
        ]
    }
```

And `home.js` is just a simple practice

``` javascript
import AOS from "aos"
require('../stylesheets/main.styl')

AOS.init({
    duration: 1000
})
```

**Comment by borysn** [comment] 2016-10-05 15:39
@silveryiris I've been trying to work out a similar issue with moving to webpack 2.1.0-beta.23-25. I'm not exactly sure the problem is with bootstrap-loader, though the stack trace originates with the package. The issue could be stemming from loaders not ready for the new webpack configuration.

My particular error

```
 69% building modules 1180/1181 modules 1 active ...ode_modules/bootstrap-loader/no-op.jsTypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:495:3)
    at Object.onRender (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/index.js:282:42)
    at /home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:2231:35
    at arrayEach (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:1357:13)
    at Object.<anonymous> (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:2223:17)
    at Object.<anonymous> (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:338:31)
    at Object.callback (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:847:20)
    at options.success (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/node-sass/lib/index.js:309:32)
```

Haven't been able to figure out yet what to do from here.

**Comment by justin808** [comment] 2016-10-06 05:06
@Judahmeek Maybe the issue is dependent on the version of webpack? In order to fix this, we need a simple reproduction case.

**Comment by justin808** [comment] 2016-10-06 05:07
@silveryiris @borysn If you can submit a PR for a fix, that would be great.

**Comment by borysn** [comment] 2016-10-06 19:49
@justin808 I'm going to try and figure out a fix, but I'm having a hard time understanding what exactly is the issue here. The issue is definitely dependent on the webpack version, 2.1.0-beta.23-25 had breaking changes.

For the simple reproduction case, should I just grab the [basic example](https://github.com/shakacode/bootstrap-loader/tree/master/examples/basic) and make the webpack changes?

**Comment by justin808** [comment] 2016-10-06 21:31
Yes! @borysn Perfect.

The issue with a fix is that it might break older webpack. Maybe, maybe not. Check out these notes: https://forum.shakacode.com/t/debugging-nodejs-and-webpack-loaders/142

**Comment by borysn** [comment] 2016-10-08 19:20
@justin808 I've been struggling to reproduce the issue with the basic example. Updating to webpack 2.1.0-beta.25 does not break the build. I'm scratching my head here a little. Could be a sign that the real cause of the errors may be related to other webpack configuration options? Not sure.

**Comment by silveryiris** [comment] 2016-10-11 09:51
Just getting back from the Taiwan national holidays.

I successed make the same error result after another small test this afternoon.


`at Object.resolveUrlLoader (PROJECT_LOCATION\node_modules\resolve-url-loader\index.js:38:55) `

This problem is caused by webpack 2 config with `resolve-url-loader`  for sure.

`console.log(loader.options)` in `function resolveUrlLoader` displayed only `context` is given.

So I make a duplicate output path setting on my  `new webpack.LoaderOptionsPlugin()`

``` javascript
  new webpack.LoaderOptionsPlugin({
            options: {
                context: __dirname,
                output: { path :  "YOUR_DIST_PATH" }
            }
  })
```

No more `Cannot read property 'path' of undefined` errors as result now!

Sorry for the misleading.

I should do the backtrace when I don't know what to do next time.

**Comment by borysn** [comment] 2016-10-17 16:06
@silveryiris glad to hear that you got your issues resolved. Seems that it is definitely different from what I am experiencing.

@justin808 I'm going to open up a separate issue for my specific problem. Still trying to figure out what's going on.

**Comment by LiTiang** [comment] 2016-10-24 07:59
Hi, @silveryiris

i use u sol, but still not work for me ...

My proj is based on [angular2-webpack -starter](https://github.com/AngularClass/angular2-webpack-starter)

this is partial content of my **webpack.common.js** configuration

```javascript
{
    test: /\.scss$/,
    exclude: /node_modules/,
    use: [
            'css-to-string-loader',
            'css-loader',
            'resolve-url-loader',
            'sass-loader'
    ]
}
plugins: [
     new LoaderOptionsPlugin({
              options: {
                    context: __dirname,
                    output: {
                       path: path.join(__dirname, 'dist')
                    }
              }
     }
]
```

I still get **Module build failed: TypeError: Cannot read property 'path' of undefined**

Please help !

**Comment by silveryiris** [comment] 2016-10-24 09:00
```javascript
        new webpack.LoaderOptionsPlugin({
            options: {
                context: __dirname,
                output: {
                    path: "YOUR_DIST_PATH"
                }
            }
        }),
```

@LiTiang Sorry it's my bad , was miss typed the  https://github.com/shakacode/bootstrap-loader/issues/185#issuecomment-252864188

Move out the "context: __dirname" from `output` object like above code.

**Comment by LiTiang** [comment] 2016-10-24 10:37
THX, @silveryiris, 

I finally solved the problem, 

but encounter another problem ="= ...

anyway, thanks again

**Closed** 2016-11-14 03:34 UTC
Labels: question

**Comment by ohenrik** [comment] 2016-11-17 14:30
@LiTiang What was your final solution to this?

**Comment by justin808** [comment] 2016-12-10 19:49
@ohenrik Did you try upgrading?

**Comment by Abhijith-Nagaraja** [comment] 2016-12-10 20:01
This issue is related to issue 191.
https://github.com/shakacode/bootstrap-loader/issues/191
