### ISSUE TITLE
style Issue on first page load and while refreshing   

### ISSUE THREAD

**Issue by FakhruddinAbdi** [shakacode/bootstrap-loader#70] opened 2016-03-12 10:09 UTC
My react app on the first load is styleless for about a second then Bootstrap get loaded.
I'm using bootstrap-loader with react-starter-kit and browserSync

How to fix it ?

**Comment by alexfedoseev** [comment] 2016-03-12 10:43
@FakhruddinAbdi I assume you use it in isomorphic app. I'm not familiar with browserSync but I guess it's the same as how webpack hot middleware works. If it's so then it's not related to `bootstrap-loader`. Your styles are placed in the DOM via JS, so they can be hot reloadable. Browser needs to parse JS and apply styles. While it's doing this — you see styleless DOM nodes, which were rendered on server.

You don't have to worry about it, since it's only applied to development environment. For production build you probably use [`extract-text-webpack-plugin`](https://github.com/webpack/extract-text-webpack-plugin) and your styles will be loaded before DOM body and applied in common way (via `link` tag, not via JS), thus users of your site/app won't see unstyled DOM.

If my assertions are right, please, close an issue.

**Comment by FakhruddinAbdi** [comment] 2016-03-12 10:52
Thanks @alexfedoseev for your comprehensive answer, it's quite right
I'm using isomorphic app and it's placing the styles in the DOM.

**Comment by FakhruddinAbdi** [comment] 2016-05-29 20:34
Unfortunately the solution didn't work in the production mode. 
As i told you i'm using [react starter kit](https://github.com/kriasoft/react-starter-kit). 
 according your first-page doc, i have to require it in the entry component. i tried it in the App.js but came across the below error 

```
webpack: bundle is now VALID.
Error: Cannot find module './lib/bootstrap.loader!./no-op.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:36
```

the other way is adding into webpack.config.js in the entry configuration section... it will load the bootstrap-loader, but with the styleless issue

**Comment by justin808** [comment] 2016-06-26 00:11
@FakhruddinAbdi Can we close this issue?

**Comment by FaxradinAbdi** [comment] 2016-06-26 00:18
@justin808 I stil have a problem with this issue 
I have gone through [this thread](https://github.com/shakacode/bootstrap-loader/issues/41) but didn't fix it.

Could you please help me fix that, otherwise i have think about alternative for bootstrap-loader
let me know if you need further information

**Comment by FaxradinAbdi** [comment] 2016-06-26 00:22
You can see this issue [here](demo.zeyton.com:8080)

**Comment by justin808** [comment] 2016-06-26 02:56
@FakhruddinAbdi I think you really need to debug your webpack setup, and that's probably not a bootstrap-loader issue.

**Closed by justin808** 2016-06-26 02:56 UTC
Labels: question

**Comment by FaxradinAbdi** [comment] 2016-06-26 09:26
I don't think its due to my webpack configuration, @justin808 

I'm using [React starter kit](https://github.com/kriasoft/react-starter-kit) which is the most popular Kit for react. 

I just tested it again with the fresh install of [React starter kit](https://github.com/kriasoft/react-starter-kit) but still i'm seeing the problem.

Could you please try reproducing this issue over fresh install of  [React starter kit](https://github.com/kriasoft/react-starter-kit)

**Comment by alexfedoseev** [comment] 2016-06-26 09:59
> I don't think its due to my webpack configuration

But I think it is. 

@FakhruddinAbdi Can you post here how you setup [`extract-text-webpack-plugin`](https://github.com/webpack/extract-text-webpack-plugin) for your production build? Since you are talking about "fresh install of React starter kit", then I think you haven't done it.

Please, spend some time to re-read my previous comment and learn how boilerplate you are using actually works (and never use it if you don't understand its internals).

I will give you some hints:

* learn how your css is actually loaded and applied in your app in all environments.
* learn how [`extract-text-webpack-plugin`](https://github.com/webpack/extract-text-webpack-plugin) works and why it must be used to resolve your issue

I'll keep this closed, since it's not an issue w/ `bootstrap-loader`, but w/ understanding how to configure frontend builds in general.
