### ISSUE TITLE
Module build failed: TypeError: Object style,css,sass has no method 'find'

### ISSUE THREAD

**Issue by AllenFang** [shakacode/bootstrap-loader#14] opened 2016-01-06 05:34 UTC
when I use <code>bootstrap-loader</code> to package my product production, I got the following error

```bash
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module build failed: TypeError: Object style,css,sass has no method 'find'
    at exports.default (/home/user1/varOne3/varOne/varOne-web/src/main/webapp/node_modules/bootstrap-loader/lib/utils/processStyleLoaders.js:20:28)
    at Object.module.exports.pitch (/home/user1/varOne3/varOne/varOne-web/src/main/webapp/node_modules/bootstrap-loader/lib/bootstrap.loader.js:107:91)
 @ ./~/bootstrap-loader/extractStyles.js 1:0-58
```
I used <code>node@0.10.25</code> or <code>node@0.12.0</code>, this issue still remain
But if I upgrade nodejs to <code>4.0.0</code>, this issues disappear

**Comment by justin808** [comment] 2016-01-06 06:34
Duplicate of #13.

**Closed by justin808** 2016-01-06 06:34 UTC

**Comment by AllenFang** [comment] 2016-01-06 09:57
Sorry for that, wait for fixing. Thanks:)
